# Generated by Django 4.0.4 on 2022-06-29 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.IntegerField(verbose_name='Numero de contacto')),
                ('correo', models.EmailField(max_length=254)),
                ('metodo_pago', models.IntegerField(choices=[[0, 'Transferencia bancaria'], [1, 'Tarjeta de debito'], [2, 'Tarjeta de crédito']])),
                ('cupon', models.IntegerField(verbose_name='Cupon de descuento')),
            ],
        ),
    ]
