# Generated by Django 4.0.4 on 2022-07-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_estado_despacho'),
    ]

    operations = [
        migrations.RenameField(
            model_name='despacho',
            old_name='apellido',
            new_name='apellidoCliente',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='correo',
            new_name='correoCliente',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='nombre',
            new_name='nombreCliente',
        ),
        migrations.RenameField(
            model_name='despacho',
            old_name='telefono',
            new_name='telefonoCliente',
        ),
        migrations.RenameField(
            model_name='estado',
            old_name='nombre',
            new_name='nombreEstado',
        ),
        migrations.AddField(
            model_name='despacho',
            name='metodo_pago',
            field=models.IntegerField(choices=[[0, 'Transferencia bancaria'], [1, 'Tarjeta de debito'], [2, 'Tarjeta de crédito']], null=True),
        ),
    ]
