# Generated by Django 4.0.4 on 2022-07-07 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_apellido_despacho_apellidocliente_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estado',
            new_name='Estado_despacho',
        ),
    ]
