# Generated by Django 4.0.4 on 2022-07-07 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_estado_estado_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='despacho',
            name='direccionCliente',
            field=models.TextField(null=True, verbose_name='Direccion del cliente'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='apellidoCliente',
            field=models.CharField(max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='correoCliente',
            field=models.EmailField(max_length=254, verbose_name='Correo electronico'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='nombreCliente',
            field=models.CharField(max_length=50, verbose_name='Nombre del cliente'),
        ),
        migrations.AlterField(
            model_name='despacho',
            name='telefonoCliente',
            field=models.IntegerField(verbose_name='Numero telefonico'),
        ),
    ]
