# Generated by Django 4.0.5 on 2022-07-08 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_despacho_direccioncliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescuentoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Descuento del producto')),
                ('nombreProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DescuentoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Descuento de la categoria')),
                ('nombreCat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.categoria')),
            ],
        ),
    ]
