# Generated by Django 4.0.4 on 2022-07-07 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_despacho_direccioncliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datos',
            name='cupon',
        ),
    ]
