# Generated by Django 4.0.5 on 2022-07-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_studentdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del banco')),
            ],
        ),
        migrations.DeleteModel(
            name='StudentData',
        ),
    ]
