# Generated by Django 4.0.5 on 2022-07-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_cuenta'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bancoCliente', models.CharField(max_length=50, verbose_name='Banco del cliente')),
                ('tipo_cuenta', models.CharField(max_length=50, verbose_name='Tipo de cuenta')),
                ('numeroCuenta', models.IntegerField(default='null', verbose_name='numero de cuenta')),
            ],
        ),
        migrations.DeleteModel(
            name='Banco',
        ),
        migrations.DeleteModel(
            name='Cuenta',
        ),
    ]
