# Generated by Django 4.0.5 on 2022-07-08 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_metodopago_numerocuenta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MetodoPago',
        ),
    ]
