# Generated by Django 4.0.5 on 2022-07-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_metodopago'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bancoCliente', models.CharField(choices=[('SELECCIONAR BANCO', 'SELECCIONAR BANCO'), ('BANCO DE CHILE', 'BANCO DE CHILE'), ('BANCO INTERNACIONAL', 'BANCO INTERNACIONAL'), ('SCOTIABANK CHILE', 'SCOTIABANK CHILE'), ('BANCO DE CREDITO E INVERSIONES', 'BANCO DE CREDITO E INVERSIONES'), ('BANCO BICE', 'BANCO BICE'), ('HSBC BANK (CHILE)', 'HSBC BANK (CHILE)'), ('BANCO SANTANDER-CHILE', 'BANCO SANTANDER-CHILE'), ('ITAU CORPBANCA', 'ITAU CORPBANCA'), ('BANCO SECURITY', 'BANCO SECURITY'), ('BANCO FALABELLA', 'BANCO FALABELLA'), ('BANCO RIPLEY', 'BANCO RIPLEY'), ('BANCO CONSORCIO', 'BANCO CONSORCIO'), ('SCOTIABANK AZUL', 'SCOTIABANK AZUL'), ('BANCO BTG PACTUAL CHILE', 'BANCO BTG PACTUAL CHILE')], default='SELECCIONAR BANCO', max_length=50)),
                ('tipo_cuenta', models.IntegerField(choices=[(100, 'SELECCIONAR TIPO DE CUENTA'), (101, 'TARJETA DE DEBITO'), (102, 'TARJETA DE CREDITO')], default=0)),
                ('numeroCuenta', models.IntegerField(null=True, verbose_name='numero de cuenta')),
            ],
        ),
    ]
